services:
    gos_pubsub_router.router:
        class: Gos\Bundle\PubSubRouterBundle\Router\Router
        arguments:
            - @gos_pubsub_router.collection
            - @gos_pubsub_router.matcher
            - @gos_pubsub_router.generator
            - @gos_pubsub_route.loader

    gos_pubsub_router.yaml.loader:
        class: Gos\Bundle\PubSubRouterBundle\Loader\YamlFileLoader
        public: false
        arguments:
            - @file_locator

    gos_pubsub_router.collection:
        class: Gos\Bundle\PubSubRouterBundle\Router\RouteCollection

    gos_pubsub_route.loader:
        class: Gos\Bundle\PubSubRouterBundle\Loader\RouteLoader
        public: false
        arguments:
            - @gos_pubsub_router.collection
            - %kernel.cache_dir%
            - %kernel.debug%
        tags:
            - { name: kernel.cache_warmer }

    gos_pubsub_router.debug.command:
        class: Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand
        arguments:
            - @gos_pubsub_router.router
        tags:
            - { name: console.command }

    gos_pubsub_router.tokenizer:
        class: Gos\Bundle\PubSubRouterBundle\Tokenizer\Tokenizer
        public: false

    gos_pubsub_router.matcher:
        class: Gos\Bundle\PubSubRouterBundle\Matcher\Matcher
        arguments:
            - @gos_pubsub_router.collection
            - @gos_pubsub_router.tokenizer

    gos_pubsub_router.generator:
        class: Gos\Bundle\PubSubRouterBundle\Generator\Generator
        arguments:
            - @gos_pubsub_router.collection
            - @gos_pubsub_router.tokenizer

    gos_pubsub_router.dumper.redis:
        class: Gos\Bundle\PubSubRouterBundle\Dumper\RedisDumper
        arguments:
            - @gos_pubsub_router.collection
            - @gos_pubsub_router.generator
            - @gos_pubsub_router.tokenizer
